
import galtox.Time.TimeScan;
import java.awt.Color;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author zubaidi
 */
public class FormSoalTRB extends javax.swing.JFrame {
    
    int total_benar, nilai;
    String status;
    SimpleDateFormat sdf = new SimpleDateFormat("dd MMMM yyyy / HH:mm");
    Date date;
    
    private Timer timer;
    private int seconds = 0, minutes = 0, hours = 0;
    private int interval = 1000;
    /**
     * Creates new form FormSoal
     */
    public FormSoalTRB() {
        initComponents();
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("Logo_SA.png")));
        jawaban1.add(rbJawaban1A);
        jawaban1.add(rbJawaban1B);
        jawaban1.add(rbJawaban1C);
        jawaban1.add(rbJawaban1D);
        jawaban2.add(rbJawaban2A);
        jawaban2.add(rbJawaban2B);
        jawaban2.add(rbJawaban2C);
        jawaban2.add(rbJawaban2D);
        jawaban3.add(rbJawaban3A);
        jawaban3.add(rbJawaban3B);
        jawaban3.add(rbJawaban3C);
        jawaban3.add(rbJawaban3D);
        jawaban4.add(rbJawaban4A);
        jawaban4.add(rbJawaban4B);
        jawaban4.add(rbJawaban4C);
        jawaban4.add(rbJawaban4D);
        jawaban5.add(rbJawaban5A);
        jawaban5.add(rbJawaban5B);
        jawaban5.add(rbJawaban5C);
        jawaban5.add(rbJawaban5D);
        jawaban6.add(rbJawaban6A);
        jawaban6.add(rbJawaban6B);
        jawaban6.add(rbJawaban6C);
        jawaban6.add(rbJawaban6D);
        jawaban7.add(rbJawaban7A);
        jawaban7.add(rbJawaban7B);
        jawaban7.add(rbJawaban7C);
        jawaban7.add(rbJawaban7D);
        jawaban8.add(rbJawaban8A);
        jawaban8.add(rbJawaban8B);
        jawaban8.add(rbJawaban8C);
        jawaban8.add(rbJawaban8D);
        jawaban9.add(rbJawaban9A);
        jawaban9.add(rbJawaban9B);
        jawaban9.add(rbJawaban9C);
        jawaban9.add(rbJawaban9D);
        jawaban10.add(rbJawaban10A);
        jawaban10.add(rbJawaban10B);
        jawaban10.add(rbJawaban10C);
        jawaban10.add(rbJawaban10D);
        date = new Date();
        labelTglUjian.setText(sdf.format(date)+" WIB");
        initMulai();
        jPanel2.setVisible(false);
        btnSelesai.setEnabled(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jawaban1 = new javax.swing.ButtonGroup();
        jawaban2 = new javax.swing.ButtonGroup();
        jawaban3 = new javax.swing.ButtonGroup();
        jawaban4 = new javax.swing.ButtonGroup();
        jawaban5 = new javax.swing.ButtonGroup();
        jawaban6 = new javax.swing.ButtonGroup();
        jawaban7 = new javax.swing.ButtonGroup();
        jawaban8 = new javax.swing.ButtonGroup();
        jawaban9 = new javax.swing.ButtonGroup();
        jawaban10 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnMulai = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        labelTimer = new javax.swing.JLabel();
        labelNamaa = new javax.swing.JLabel();
        labelNama = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        labelTglUjian = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        labelJurusan = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        soal4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        rbJawaban4A = new javax.swing.JRadioButton();
        rbJawaban4B = new javax.swing.JRadioButton();
        rbJawaban4C = new javax.swing.JRadioButton();
        rbJawaban4D = new javax.swing.JRadioButton();
        soal3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        rbJawaban3A = new javax.swing.JRadioButton();
        rbJawaban3B = new javax.swing.JRadioButton();
        rbJawaban3C = new javax.swing.JRadioButton();
        rbJawaban3D = new javax.swing.JRadioButton();
        soal2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        rbJawaban2A = new javax.swing.JRadioButton();
        rbJawaban2B = new javax.swing.JRadioButton();
        rbJawaban2C = new javax.swing.JRadioButton();
        rbJawaban2D = new javax.swing.JRadioButton();
        soal1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        rbJawaban1A = new javax.swing.JRadioButton();
        rbJawaban1B = new javax.swing.JRadioButton();
        rbJawaban1C = new javax.swing.JRadioButton();
        rbJawaban1D = new javax.swing.JRadioButton();
        soal5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        rbJawaban6A = new javax.swing.JRadioButton();
        rbJawaban6B = new javax.swing.JRadioButton();
        rbJawaban6C = new javax.swing.JRadioButton();
        rbJawaban6D = new javax.swing.JRadioButton();
        soal6 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        rbJawaban5A = new javax.swing.JRadioButton();
        rbJawaban5B = new javax.swing.JRadioButton();
        rbJawaban5C = new javax.swing.JRadioButton();
        rbJawaban5D = new javax.swing.JRadioButton();
        soal7 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        rbJawaban7A = new javax.swing.JRadioButton();
        rbJawaban7B = new javax.swing.JRadioButton();
        rbJawaban7C = new javax.swing.JRadioButton();
        rbJawaban7D = new javax.swing.JRadioButton();
        soal9 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        rbJawaban8A = new javax.swing.JRadioButton();
        rbJawaban8B = new javax.swing.JRadioButton();
        rbJawaban8C = new javax.swing.JRadioButton();
        rbJawaban8D = new javax.swing.JRadioButton();
        soal8 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        rbJawaban10A = new javax.swing.JRadioButton();
        rbJawaban10B = new javax.swing.JRadioButton();
        rbJawaban10C = new javax.swing.JRadioButton();
        rbJawaban10D = new javax.swing.JRadioButton();
        btnSelesai = new javax.swing.JButton();
        soal10 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        rbJawaban9A = new javax.swing.JRadioButton();
        rbJawaban9B = new javax.swing.JRadioButton();
        rbJawaban9C = new javax.swing.JRadioButton();
        rbJawaban9D = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("APLIKASI TEST PPDB SMK SYAFI'I AKROM");
        setResizable(false);

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logo_SA.png"))); // NOI18N

        btnMulai.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        btnMulai.setText("Mulai Test");
        btnMulai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMulaiActionPerformed(evt);
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, " Waktu Mengerjakan ", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 11))); // NOI18N

        labelTimer.setFont(new java.awt.Font("Segoe UI", 0, 43)); // NOI18N
        labelTimer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTimer.setText("00:00");
        labelTimer.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTimer, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTimer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        labelNamaa.setFont(new java.awt.Font("Segoe UI Semibold", 0, 32)); // NOI18N
        labelNamaa.setText("SELAMAT DATANG");

        labelNama.setFont(new java.awt.Font("Segoe UI Semibold", 0, 32)); // NOI18N
        labelNama.setText("jLabel2");

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        jLabel4.setText("Waktu Ujian:");

        labelTglUjian.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        labelTglUjian.setText("jLabel2");

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        jLabel2.setText("Jurusan:");

        labelJurusan.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        labelJurusan.setText("jLabel2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelTglUjian)
                            .addComponent(labelJurusan))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnMulai, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelNamaa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelNama)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(labelNamaa)
                                    .addComponent(labelNama))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(35, 35, 35)
                                        .addComponent(btnMulai, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(labelTglUjian)
                                            .addComponent(jLabel4))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(labelJurusan)
                                            .addComponent(jLabel2))))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("4. 43 x 3 = ...");

        rbJawaban4A.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rbJawaban4A.setText("89");

        rbJawaban4B.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rbJawaban4B.setText("109");

        rbJawaban4C.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rbJawaban4C.setText("129");

        rbJawaban4D.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rbJawaban4D.setText("139");

        javax.swing.GroupLayout soal4Layout = new javax.swing.GroupLayout(soal4);
        soal4.setLayout(soal4Layout);
        soal4Layout.setHorizontalGroup(
            soal4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(soal4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(soal4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(soal4Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(rbJawaban4A)
                        .addGap(88, 88, 88)
                        .addComponent(rbJawaban4B)
                        .addGap(113, 113, 113)
                        .addComponent(rbJawaban4C)
                        .addGap(106, 106, 106)
                        .addComponent(rbJawaban4D))
                    .addComponent(jLabel7))
                .addContainerGap(473, Short.MAX_VALUE))
        );
        soal4Layout.setVerticalGroup(
            soal4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(soal4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(soal4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbJawaban4A)
                    .addComponent(rbJawaban4B)
                    .addComponent(rbJawaban4C)
                    .addComponent(rbJawaban4D))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("3. x + 7 = 11. x = ...");

        rbJawaban3A.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rbJawaban3A.setText("3");

        rbJawaban3B.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rbJawaban3B.setText("18");

        rbJawaban3C.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rbJawaban3C.setText("11/7");

        rbJawaban3D.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rbJawaban3D.setText("6");

        javax.swing.GroupLayout soal3Layout = new javax.swing.GroupLayout(soal3);
        soal3.setLayout(soal3Layout);
        soal3Layout.setHorizontalGroup(
            soal3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(soal3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(soal3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(soal3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(rbJawaban3A)
                        .addGap(94, 94, 94)
                        .addComponent(rbJawaban3B)
                        .addGap(120, 120, 120)
                        .addComponent(rbJawaban3C)
                        .addGap(103, 103, 103)
                        .addComponent(rbJawaban3D))
                    .addComponent(jLabel6))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        soal3Layout.setVerticalGroup(
            soal3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(soal3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(soal3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbJawaban3A)
                    .addComponent(rbJawaban3B)
                    .addComponent(rbJawaban3C)
                    .addComponent(rbJawaban3D))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("2. 3n = 15. n = ...");

        rbJawaban2A.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rbJawaban2A.setText("5");

        rbJawaban2B.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rbJawaban2B.setText("3");

        rbJawaban2C.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rbJawaban2C.setText("10");

        rbJawaban2D.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rbJawaban2D.setText("18");

        javax.swing.GroupLayout soal2Layout = new javax.swing.GroupLayout(soal2);
        soal2.setLayout(soal2Layout);
        soal2Layout.setHorizontalGroup(
            soal2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(soal2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(soal2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(soal2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(rbJawaban2A)
                        .addGap(95, 95, 95)
                        .addComponent(rbJawaban2B)
                        .addGap(125, 125, 125)
                        .addComponent(rbJawaban2C)
                        .addGap(117, 117, 117)
                        .addComponent(rbJawaban2D))
                    .addComponent(jLabel5))
                .addContainerGap(449, Short.MAX_VALUE))
        );
        soal2Layout.setVerticalGroup(
            soal2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(soal2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(soal2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbJawaban2A)
                    .addComponent(rbJawaban2B)
                    .addComponent(rbJawaban2C)
                    .addComponent(rbJawaban2D))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("1. 3/7 x 1/3 = n, n = ...");

        rbJawaban1A.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rbJawaban1A.setText("1/7");

        rbJawaban1B.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rbJawaban1B.setText("4/21");

        rbJawaban1C.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rbJawaban1C.setText("4/10");

        rbJawaban1D.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rbJawaban1D.setText("2/5");

        javax.swing.GroupLayout soal1Layout = new javax.swing.GroupLayout(soal1);
        soal1.setLayout(soal1Layout);
        soal1Layout.setHorizontalGroup(
            soal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(soal1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(soal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(soal1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(rbJawaban1A)
                        .addGap(79, 79, 79)
                        .addComponent(rbJawaban1B)
                        .addGap(111, 111, 111)
                        .addComponent(rbJawaban1C)
                        .addGap(104, 104, 104)
                        .addComponent(rbJawaban1D))
                    .addComponent(jLabel3))
                .addContainerGap(452, Short.MAX_VALUE))
        );
        soal1Layout.setVerticalGroup(
            soal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(soal1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(soal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbJawaban1A)
                    .addComponent(rbJawaban1B)
                    .addComponent(rbJawaban1C)
                    .addComponent(rbJawaban1D))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("6. 3x = 18. x = ...");

        rbJawaban6A.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rbJawaban6A.setText("4");

        rbJawaban6B.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rbJawaban6B.setText("5");

        rbJawaban6C.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rbJawaban6C.setText("6");

        rbJawaban6D.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rbJawaban6D.setText("7");

        javax.swing.GroupLayout soal5Layout = new javax.swing.GroupLayout(soal5);
        soal5.setLayout(soal5Layout);
        soal5Layout.setHorizontalGroup(
            soal5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(soal5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(soal5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(soal5Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(rbJawaban6A)
                        .addGap(96, 96, 96)
                        .addComponent(rbJawaban6B)
                        .addGap(123, 123, 123)
                        .addComponent(rbJawaban6C)
                        .addGap(124, 124, 124)
                        .addComponent(rbJawaban6D))
                    .addComponent(jLabel8))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        soal5Layout.setVerticalGroup(
            soal5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(soal5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(soal5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbJawaban6A)
                    .addComponent(rbJawaban6B)
                    .addComponent(rbJawaban6C)
                    .addComponent(rbJawaban6D))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("5. 95 / 5 = ...");

        rbJawaban5A.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rbJawaban5A.setText("12");

        rbJawaban5B.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rbJawaban5B.setText("13");

        rbJawaban5C.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rbJawaban5C.setText("14");

        rbJawaban5D.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rbJawaban5D.setText("19");
        rbJawaban5D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbJawaban5DActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout soal6Layout = new javax.swing.GroupLayout(soal6);
        soal6.setLayout(soal6Layout);
        soal6Layout.setHorizontalGroup(
            soal6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(soal6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(soal6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(soal6Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(rbJawaban5A)
                        .addGap(89, 89, 89)
                        .addComponent(rbJawaban5B)
                        .addGap(120, 120, 120)
                        .addComponent(rbJawaban5C)
                        .addGap(114, 114, 114)
                        .addComponent(rbJawaban5D))
                    .addComponent(jLabel9))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        soal6Layout.setVerticalGroup(
            soal6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(soal6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(soal6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbJawaban5A)
                    .addComponent(rbJawaban5B)
                    .addComponent(rbJawaban5C)
                    .addComponent(rbJawaban5D))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("7. 978 - 122 = ...");

        rbJawaban7A.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rbJawaban7A.setText("756");

        rbJawaban7B.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rbJawaban7B.setText("856");

        rbJawaban7C.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rbJawaban7C.setText("566");

        rbJawaban7D.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rbJawaban7D.setText("496");
        rbJawaban7D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbJawaban7DActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout soal7Layout = new javax.swing.GroupLayout(soal7);
        soal7.setLayout(soal7Layout);
        soal7Layout.setHorizontalGroup(
            soal7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(soal7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(soal7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(soal7Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(rbJawaban7A)
                        .addGap(81, 81, 81)
                        .addComponent(rbJawaban7B)
                        .addGap(109, 109, 109)
                        .addComponent(rbJawaban7C)
                        .addGap(113, 113, 113)
                        .addComponent(rbJawaban7D))
                    .addComponent(jLabel10))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        soal7Layout.setVerticalGroup(
            soal7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(soal7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(soal7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbJawaban7A)
                    .addComponent(rbJawaban7B)
                    .addComponent(rbJawaban7C)
                    .addComponent(rbJawaban7D))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setText("8. 2a - 9 = b. Jika b = 5, maka a = ...");

        rbJawaban8A.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rbJawaban8A.setText("7");

        rbJawaban8B.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rbJawaban8B.setText("8");

        rbJawaban8C.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rbJawaban8C.setText("9");

        rbJawaban8D.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rbJawaban8D.setText("10");

        javax.swing.GroupLayout soal9Layout = new javax.swing.GroupLayout(soal9);
        soal9.setLayout(soal9Layout);
        soal9Layout.setHorizontalGroup(
            soal9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(soal9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(soal9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(soal9Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(rbJawaban8A)
                        .addGap(95, 95, 95)
                        .addComponent(rbJawaban8B)
                        .addGap(123, 123, 123)
                        .addComponent(rbJawaban8C)
                        .addGap(128, 128, 128)
                        .addComponent(rbJawaban8D))
                    .addComponent(jLabel12))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        soal9Layout.setVerticalGroup(
            soal9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(soal9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(soal9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbJawaban8A)
                    .addComponent(rbJawaban8B)
                    .addComponent(rbJawaban8C)
                    .addComponent(rbJawaban8D))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("10. 3/4 x 16 = n. n = ...");

        rbJawaban10A.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rbJawaban10A.setText("10");

        rbJawaban10B.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rbJawaban10B.setText("11");

        rbJawaban10C.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rbJawaban10C.setText("12");

        rbJawaban10D.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rbJawaban10D.setText("13");

        btnSelesai.setText("SELESAI");
        btnSelesai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelesaiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout soal8Layout = new javax.swing.GroupLayout(soal8);
        soal8.setLayout(soal8Layout);
        soal8Layout.setHorizontalGroup(
            soal8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(soal8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(soal8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(soal8Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(rbJawaban10A)
                        .addGap(91, 91, 91)
                        .addComponent(rbJawaban10B)
                        .addGap(114, 114, 114)
                        .addComponent(rbJawaban10C)
                        .addGap(122, 122, 122)
                        .addComponent(rbJawaban10D))
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSelesai, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        soal8Layout.setVerticalGroup(
            soal8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(soal8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(soal8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSelesai, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addGroup(soal8Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(soal8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbJawaban10A)
                            .addComponent(rbJawaban10B)
                            .addComponent(rbJawaban10C)
                            .addComponent(rbJawaban10D))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setText("9. 5a - 13 = 12. a = ...");

        rbJawaban9A.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rbJawaban9A.setText("4");

        rbJawaban9B.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rbJawaban9B.setText("5");

        rbJawaban9C.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rbJawaban9C.setText("6");

        rbJawaban9D.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rbJawaban9D.setText("7");

        javax.swing.GroupLayout soal10Layout = new javax.swing.GroupLayout(soal10);
        soal10.setLayout(soal10Layout);
        soal10Layout.setHorizontalGroup(
            soal10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(soal10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(soal10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(soal10Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(rbJawaban9A)
                        .addGap(96, 96, 96)
                        .addComponent(rbJawaban9B)
                        .addGap(121, 121, 121)
                        .addComponent(rbJawaban9C)
                        .addGap(128, 128, 128)
                        .addComponent(rbJawaban9D))
                    .addComponent(jLabel13))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        soal10Layout.setVerticalGroup(
            soal10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(soal10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(soal10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbJawaban9A)
                    .addComponent(rbJawaban9B)
                    .addComponent(rbJawaban9C)
                    .addComponent(rbJawaban9D))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(soal5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(soal3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(24, 24, 24))
                    .addComponent(soal6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(soal7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(soal9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(soal8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(soal10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(soal4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(soal2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(soal1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(soal1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(soal2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(soal3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(soal4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(soal6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(soal5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(soal7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(soal9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(soal10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(soal8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel3);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 998, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSelesaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelesaiActionPerformed
        // TODO add your handling code here:
        stop();
        this.setHasil();
    }//GEN-LAST:event_btnSelesaiActionPerformed

    private void btnMulaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMulaiActionPerformed
        // TODO add your handling code here:
        getIndex();
        start();
        total_benar = 0;
    }//GEN-LAST:event_btnMulaiActionPerformed

    private void rbJawaban7DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbJawaban7DActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbJawaban7DActionPerformed

    private void rbJawaban5DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbJawaban5DActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbJawaban5DActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormSoalOto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormSoalOto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormSoalOto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormSoalOto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormSoalOto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMulai;
    private javax.swing.JButton btnSelesai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.ButtonGroup jawaban1;
    private javax.swing.ButtonGroup jawaban10;
    private javax.swing.ButtonGroup jawaban2;
    private javax.swing.ButtonGroup jawaban3;
    private javax.swing.ButtonGroup jawaban4;
    private javax.swing.ButtonGroup jawaban5;
    private javax.swing.ButtonGroup jawaban6;
    private javax.swing.ButtonGroup jawaban7;
    private javax.swing.ButtonGroup jawaban8;
    private javax.swing.ButtonGroup jawaban9;
    public javax.swing.JLabel labelJurusan;
    public javax.swing.JLabel labelNama;
    public javax.swing.JLabel labelNamaa;
    private javax.swing.JLabel labelTglUjian;
    public javax.swing.JLabel labelTimer;
    private javax.swing.JRadioButton rbJawaban10A;
    private javax.swing.JRadioButton rbJawaban10B;
    private javax.swing.JRadioButton rbJawaban10C;
    private javax.swing.JRadioButton rbJawaban10D;
    private javax.swing.JRadioButton rbJawaban1A;
    private javax.swing.JRadioButton rbJawaban1B;
    private javax.swing.JRadioButton rbJawaban1C;
    private javax.swing.JRadioButton rbJawaban1D;
    private javax.swing.JRadioButton rbJawaban2A;
    private javax.swing.JRadioButton rbJawaban2B;
    private javax.swing.JRadioButton rbJawaban2C;
    private javax.swing.JRadioButton rbJawaban2D;
    private javax.swing.JRadioButton rbJawaban3A;
    private javax.swing.JRadioButton rbJawaban3B;
    private javax.swing.JRadioButton rbJawaban3C;
    private javax.swing.JRadioButton rbJawaban3D;
    private javax.swing.JRadioButton rbJawaban4A;
    private javax.swing.JRadioButton rbJawaban4B;
    private javax.swing.JRadioButton rbJawaban4C;
    private javax.swing.JRadioButton rbJawaban4D;
    private javax.swing.JRadioButton rbJawaban5A;
    private javax.swing.JRadioButton rbJawaban5B;
    private javax.swing.JRadioButton rbJawaban5C;
    private javax.swing.JRadioButton rbJawaban5D;
    private javax.swing.JRadioButton rbJawaban6A;
    private javax.swing.JRadioButton rbJawaban6B;
    private javax.swing.JRadioButton rbJawaban6C;
    private javax.swing.JRadioButton rbJawaban6D;
    private javax.swing.JRadioButton rbJawaban7A;
    private javax.swing.JRadioButton rbJawaban7B;
    private javax.swing.JRadioButton rbJawaban7C;
    private javax.swing.JRadioButton rbJawaban7D;
    private javax.swing.JRadioButton rbJawaban8A;
    private javax.swing.JRadioButton rbJawaban8B;
    private javax.swing.JRadioButton rbJawaban8C;
    private javax.swing.JRadioButton rbJawaban8D;
    private javax.swing.JRadioButton rbJawaban9A;
    private javax.swing.JRadioButton rbJawaban9B;
    private javax.swing.JRadioButton rbJawaban9C;
    private javax.swing.JRadioButton rbJawaban9D;
    private javax.swing.JPanel soal1;
    private javax.swing.JPanel soal10;
    private javax.swing.JPanel soal2;
    private javax.swing.JPanel soal3;
    private javax.swing.JPanel soal4;
    private javax.swing.JPanel soal5;
    private javax.swing.JPanel soal6;
    private javax.swing.JPanel soal7;
    private javax.swing.JPanel soal8;
    private javax.swing.JPanel soal9;
    // End of variables declaration//GEN-END:variables

    private void setHasil(){
        if(rbJawaban1A.isSelected()){
            total_benar += 1;
        }else{
            total_benar += 0;
        }
        
        if(rbJawaban2A.isSelected()){
            total_benar += 1;
        }else{
            total_benar += 0;
        }
        
        if(rbJawaban3A.isSelected()){
            total_benar += 1;
        }else{
            total_benar += 0;
        }
        
        if(rbJawaban4C.isSelected()){
            total_benar += 1;
        }else{
            total_benar += 0;
        }
        
        if(rbJawaban5D.isSelected()){
            total_benar += 1;
        }else{
            total_benar += 0;
        }
        
        if(rbJawaban6C.isSelected()){
            total_benar += 1;
        }else{
            total_benar += 0;
        }
        
        if(rbJawaban7B.isSelected()){
            total_benar += 1;
        }else{
            total_benar += 0;
        }
        
        if(rbJawaban8A.isSelected()){
            total_benar += 1;
        }else{
            total_benar += 0;
        }
        
        if(rbJawaban9B.isSelected()){
            total_benar += 1;
        }else{
            total_benar += 0;
        }
        
        if(rbJawaban10C.isSelected()){
            total_benar += 1;
        }else{
            total_benar += 0;
        }
        
        if(total_benar > 5){
            status = "<HTML><b><FONT SIZE='12'>SELAMAT KAMU BERHASIL";
        }else{
            status = "<HTML><b><FONT SIZE='12' COLOR='RED'>MAAF KAMU BELUM BERHASIL";
        }
        
        int conf = JOptionPane.showConfirmDialog(this, "Jawaban Benar Kamu adalah "+total_benar+".\n"+status+""
                + "\nTekan Yes Untuk Keluar | Tekan No Untuk Mengulang Mengerjakan\n"
                + "Setelah Selesai Mengerjakan, Segera Laporan ke Panitia Ya :D", 
                "Hasil Ujian", JOptionPane.YES_NO_OPTION);
        if(conf == 0){
            this.reset();
            this.simpanData();
            FormIdentitas fi = new FormIdentitas();
            fi.txtNama.requestFocus();
            fi.setVisible(true);
            this.dispose();
        }else{
            this.reset();
            btnMulai.setEnabled(true);
            total_benar = 0;
        }
        
    }

    private void reset() {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        jawaban1.clearSelection();
        jawaban10.clearSelection();
        jawaban2.clearSelection();
        jawaban3.clearSelection();
        jawaban4.clearSelection();
        jawaban5.clearSelection();
        jawaban6.clearSelection();
        jawaban7.clearSelection();
        jawaban8.clearSelection();
        jawaban9.clearSelection();
    }
    
    private void initMulai() {
        timer = new Timer(interval, new ActionListener() {

            public void actionPerformed(ActionEvent e) {
                if (seconds == 0 && (minutes > 0 || hours > 0)) {
                    seconds = 59;
                    minutes--;
                } else {
                    seconds--;
                }
                if (minutes == 0 && hours > 0) {
                    minutes = 59;
                    hours--;
                }
                if (seconds == 0 && minutes == 0 && hours == 0) {
                    seconds = minutes = hours = 0;
                    labelTimer.setText("SELESAI");
                    setHasil();
                }
                TimeScan ts = new TimeScan(seconds, minutes, hours);
                if (minutes >= 0 && hours > 0 && seconds >= 0) {
                    labelTimer.setText(ts.getHours() + ":" + ts.getMinutes() + ":" + ts.getSeconds());
                } else if (minutes > 0 && seconds >= 0 && hours <= 0) {
                    labelTimer.setText(ts.getMinutes() + ":" + ts.getSeconds());
                } else if (minutes == 0 && hours == 0 && seconds > 0) {
                    if (seconds > 10) {
                        labelTimer.setText(ts.getSeconds());
                    } else {
                        labelTimer.setText(String.valueOf(seconds));
                        labelTimer.setForeground(Color.red);
                    }
                }
            }
        });
    }
    
    private void getIndex() {
        seconds = hours = 0;
        minutes = 10;
    }
    
    private void start(){
        timer.start();
        btnSelesai.setEnabled(true);
        btnMulai.setEnabled(false);
        jPanel2.setVisible(true);
    }
    
    private void stop(){
        timer.stop();
        btnSelesai.setEnabled(false);
        btnMulai.setEnabled(true);
    }
    
    private void simpanData(){
        String file = "./Hasil.txt";
        String nama = labelNama.getText();
        String jur = labelJurusan.getText();
        int total = total_benar;
        String waktu = labelTglUjian.getText();
        BufferedWriter writer = null;
        try {
            writer = new BufferedWriter(new FileWriter(file, true));
            writer.write(nama+"; "+jur+"; "+String.valueOf(total)+"; "+waktu);
            writer.flush();
            writer.newLine();
            writer.close();
            //JOptionPane.showMessageDialog(rootPane, "OK");
        } catch (IOException ex) {
            Logger.getLogger(FormSoalOto.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(rootPane, "Gagal Simpan");
        } finally {
            try{
                if (writer != null)
                    writer.close();
            } catch (IOException ex) {
                Logger.getLogger(FormSoalOto.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

}
